### ISSUE TITLE
Für Booleans (true,false) je nach Datensatz entweder Deutsche oder Englische Bezeichnungen

### ISSUE THREAD

**Issue by hkirn** [NVBWSeifert/Bahnhoefe_barrierefrei#3]
Teilweise werden Booleans, also Felder die nur "ja" oder "nein" enthalten, auf Deutsch in den Datensätzen definiert, teilweise auf Englisch. Man muss also beim Einlesen der Dateien beide Möglichkeiten berücksichtigen, dadurch Gefahr von Fehlern.
Am besten wäre hier wahrscheinlich komplett auf Englisch umzustellen, außer die Daten sollen wirklich direkt lesbar sein.

Beispiel Deutsch: 
https://www.nvbw.de/fileadmin/user_upload/service/open_data/haltestellen/SPNV/BFRK_Haltesteig.csv

Beispiel Englisch:
https://www.nvbw.de/fileadmin/user_upload/service/open_data/haltestellen/SPNV/BFRK_Toilette.csv
(Englisch nach groben Überfliegen nur bei Toilette gefunden)

![deutschHaltesteig](https://user-images.githubusercontent.com/96598824/153063329-815a79e2-e350-41d3-9296-cc9321056b17.png)

![englischToilette](https://user-images.githubusercontent.com/96598824/153063736-d82cff12-5633-4d09-b4ba-8d474257ca54.png)

**Comment by NVBWSeifert** [comment]
Mit Verzögerung jetzt endlich durchgängige Ausgabe ja/nein in booleaschen Feldern
