### ISSUE TITLE
Foto Fahrscheinautomat auf Haltesteig nicht in Datensatz

### ISSUE THREAD

**Issue by hkirn** [NVBWSeifert/Bahnhoefe_barrierefrei#5]
Hier bin ich mir nicht sicher, ob es sich hierbei um einen Bug handelt, oder ob das so gewollt ist.

Im Datensatz Haltesteig existiert keine URL zum Fahrkartenautomat und im Datensatz Fahrkartenautomat erscheinen Automaten auf dem Haltesteig nicht.

Kann auch so beabsichtigt sein, deshalb nur ein Hinweis

**Comment by NVBWSeifert** [comment]
Hallo,
die Bilder müssen von uns händisch geprüft und freigegeben werden. Zum Zeitpunkt der Erstellung des Open-Data Datensatzes wird für jede Bildreferenz geprüft, ob diese schon public-ready ist und dann wird die Referenz ergänzt.
Fehlende Bildreferenzen werden hoffentlich Kürze ergänzt
