### ISSUE TITLE
Links zu Bildern fehlerhaft (gehen in privates Netz)

### ISSUE THREAD

**Issue by hkirn** [NVBWSeifert/Bahnhoefe_barrierefrei#6]
In Version vom 28.9.2022 sind die Links fehlerhaft. Diese gehen in ein privates Netzwerk das von ausserhalb nicht erreichbar ist:

http://10.70.190.33/bfrk/haltestelle/bilder/de:08136:4817/b3aff1e8-b070-4b92-83e8-638ad427b98e.jpg

Wenn man http://10.70.190.33/* durch https://mobidata-bw.de/* ersetzt, funktioniert es wieder. Ich vermute, dass 10.70.190.33 die interne IP von dem Server ist, den man von ausserhalb ihres Netzwerks mit https://mobidata-bw.de/ erreicht.

Beispiel für eine meiner Meinung nach korrekten URL:
https://mobidata-bw.de/bfrk/haltestelle/bilder/de:08136:4817/b3aff1e8-b070-4b92-83e8-638ad427b98e.jpg

Für mein kleines "Spiel- und Übungsprojektchen" nicht schlimm, aber vielleicht verwendet schon jemand den Datensatz für etwas wichtiges, deshalb als kurzes Feedback...

noch ein kleiner Screenshot:

![grafik](https://user-images.githubusercontent.com/96598824/193558748-fa7f5196-ee74-44d4-a3e3-586549a76fac.png)

**Comment by NVBWSeifert** [comment]
Hallo hkirn,

danke für den Hinweis. Ich habe den Datensatz gestern aktualisiert, jetzt wieder mit den mobidata-Links.
viele Grüße
Dietmar Seifert
